### ISSUE TITLE
Does this repository match the published version?

### ISSUE THREAD

**Issue by PeterParslow** [opengeospatial/unggim_standards_guide#14]
The repository's readme says

"This version is based upon Edition 3 Draft, in which Review/comments were invited by 31 October 2021. "

The published version (https://standards.unggim.ogc.org/index.php) is Edition 3.0.0:2022-01-01.

If we publish again from this repository, will we lose whatever changed between the October 2021 draft and the January 2022 publication?

I've tried looking at some bits, and not all look the same. For example, the Appendix titles at https://standards.unggim.ogc.org/index.php are different to those in the adoc files in https://github.com/opengeospatial/unggim_standards_guide/tree/main/Appendices - but I'm not sure those files are used in the published online guide, where the appendices are linked spreadsheets rather than HTML files.

**Comment by ogcscotts** [comment]
request for republication has been made

**Comment by PeterParslow** [comment]
> request for republication has been made

https://standards.unggim.ogc.org/unggim_guide.html still has "ISO 19169" for API Features...

**Comment by ogcscotts** [comment]
published: https://standards.unggim.ogc.org/index.php

**Comment by PeterParslow** [comment]
Looks good. Which can't be said of the PDF version which is linked & contains the corrections, but also contains a lot of unprocessed HTML tags in places.

**Comment by PeterParslow** [comment]
@ogcscotts : is there anything we (you, Greg?) can do about the html tags in the PDF?

**Comment by ogcscotts** [comment]
@gbuehler does Asciidoctor-pdf have a problem with HTML tags that include the window="_blank" modifier?

**Comment by gbuehler** [comment]
Per https://docs.asciidoctor.org/asciidoc/latest/macros/link-macro-attribute-parsing/

the Asciidoc should be `window=_blank` without the quotes.

**Comment by gbuehler** [comment]
Note that this fix did not exactly work. 

So what I did was for the PDF version only I did a search and replace for ', window=_blank' with ''  then I ran the command:

'asciidoctor-pdf -o unggim_guide.pdf unggim.adoc'

and posted that document.  The repo still contains all the ', window=_blank' as that is needed for the HTML.

**Comment by PeterParslow** [comment]
Thanks, Greg, for sorting that out - The PDF likes good now. 

Those instructions should be stored somewhere for future use, e.g. after the IHO meeting in  March that should consider / decide on https://github.com/opengeospatial/unggim_standards_guide/issues/6. I've summarised in the Readme
