### ISSUE TITLE
Improve "definition" of "open standard"

### ISSUE THREAD

**Issue by PeterParslow** [opengeospatial/unggim_standards_guide#7]
There is text at http://standards.unggim.ogc.org/unggim_guide.html#_standards_awareness, which is cited in IGIF Part 2 SP 6:

"Open international standards are voluntary consensus-driven standards published by the SDOs. Open standards [[5](http://standards.unggim.ogc.org/unggim_guide.html#_footnotedef_5)] are developed, approved, and maintained via a collaborative and consensus-driven process and made available to the general public."

I think it is important to add that they are not just "available" to the general public, but that they can be implemented without (high) licensing fees - of course it costs to implement them: one generally has to develop or acquire software, but a defining characteristic of an "open standard" approach is that their are either no patented technologies in it, or that those patent parts are available at zero (or very low) cost.

**Comment by ghobona** [comment]
A collaborative paper by OGC and OSGeo defined it at https://wiki.osgeo.org/wiki/Open_Source_and_Open_Standards#Open_Standards

The definition has been used in a number of OGC documents.

https://opengeospatial.github.io/e-learning/ogc-standards/text/services-ogc.html#open-standards-the-definition

https://docs.ogc.org/wp/16-019r4/16-019r4.html

https://portal.ogc.org/files/?artifact_id=45126

**Comment by PeterParslow** [comment]
The problem with that one is that OGC (& OSGeo) have come down firmly on one side of an ongoing discussion - the document says "available free of charge", which (perhaps deliberately) excludes standards from ISO, IEC, ITU and others. In discussions in the UK's Open Standards Board, we have heard that OGC's current patent policy doesn't actually guarantee that the standards are "unencumbered by patents and other intellectual property." Further, under UK copyright law, copyright is a form of intellectual property & you can't have a document without copyright - I guess you can then licence it in such a way that copyright doesn't "encumber" it.

Probably a UN document needs to start by acknowledging that different countries may well have their own definition of "open standard", but that for this document (as a "child" of IGIF) the definition does include "unencumbered by patents" or at least the equivalent item 3 "no charges", but is broad enough to allow ISO, IEC & ITU standards. That said, there are charges to implement one or two well established "open" standards - I think that's still the case with TIFF? The tricky bit is who pays those charges...

**Comment by ogcscotts** [comment]
It seems to me that the original definition is best: each modification (cost of implementation, cost to purchase, patent rights guarantee, etc.) is likely just to cause confusion. Specifically to patent encumberment - does any SDO "guarantee" no such encumberment? OGC policy to join a SWG makes each participant acknowledge that any Intellectual Property (IP) that they share becomes owned by OGC. If there is a patent behind the IP, OGC will not add that content to the Standard (this has happened with DGGS).

**Comment by PeterParslow** [comment]
It is a tricky area - on the one hand I have had people argue that they can't use an open standard based implementation because of the tiny possibility that someone's patent might be hidden in there. On the other hand, I see your point that noone can entirely guarantee that is not true. It all ends up with weak words about the efforts SDOs go to to insist that patents are declared during the process - but dishonest experts could presumably sneak something in & then ambush users later, if they wanted to wreck the consensus process & reputation of that SDO.

I would really like to say something positive to cut through the FUD surrounding the "hidden costs" of implementing open standards! Mainly put about by those who want to lock people into their own solutions (whether commercial or open source).
