### ISSUE TITLE
Tier 2 "Distributed Maintenance and Use" incorrect ISO number for OGC API Features

### ISSUE THREAD

**Issue by PeterParslow** [opengeospatial/unggim_standards_guide#8]
http://standards.unggim.ogc.org/unggim_guide.html#_distributed_maintenance_and_use

Last bullet point

Says "ISO 19169"; should say "ISO 19168".

**Comment by ogcscotts** [comment]
pull request merged

**Comment by PeterParslow** [comment]
@ogcscotts: how does it get from 'merged' (into the main branch 'code') to actually changing the 'live' text at http://standards.unggim.ogc.org/unggim_guide.html#_distributed_maintenance_and_use? Is there a GitHub pipeline associated with this one, and I just have to wait? Or (perhaps more likely) does someone have to run something "manually" to recreate the HTML & PDF.
(As it seems you have write access to main, I guess that someone is you)

**Comment by ogcscotts** [comment]
@PeterParslow the updates are currently manual and will be run once the first batch of issues is cleared.

**Comment by PeterParslow** [comment]
> @PeterParslow the updates are currently manual and will be run once the first batch of issues is cleared.

@ogcscotts : the one open issue is kind of on hold until next year; at least, that's how I read IHO's input. So could we publish the two that have been fixed?
